import Head from "next/head";
import Image from "next/image";
import { Nunito } from "next/font/google";
import styles from "@/styles/Home.module.scss";

const nunito = Nunito({
  weight: ["200", "300", "400", "600", "700"],
  display: "swap",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
}
